### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by AmirSavand**
@Alir3z4 I checked https://gohugo.io/content-management/multilingual/ now when building, we have 3 folders for each language (ex: `/ru/`).

But I still don't know how to use translation for the content, need help.

### CODE REVIEW

**Comment by Alir3z4** [comment]
I see.
Let me pull and make it happen

**Comment by Alir3z4** [comment]
Updated the code and it works.
Please continue where I've left ;)

Also: html minifier has been added <3 thanks to lovely gulp

**Comment by AmirSavand** [comment]
Awesome.

**Comment by AmirSavand** [comment]
Should we add RU too?

**Comment by Alir3z4** [comment]
This is awesome yes.
Yes, add RU as well.

**Pull request merged**
