### PR TITLE
Language selection

### PR DESCRIPTION
**Pull request by AmirSavand**
image

image

image

image

image

### CODE REVIEW

**Comment by AmirSavand** [comment]
So what's the status of this pull?

**Comment by Alir3z4** [comment]
Ok, just convert all the i18n file to JSON.
This is approved by me.
Please have a look at feel free to merge.

**Comment by AmirSavand** [comment]
The JSON files could be formatted but it's all good.

**Comment by AmirSavand** [comment]
Much better.

**Pull request merged**
