### PR TITLE
Hugo

### LINKED ISSUE #20: Using Hugo static site builder
Mainly because it makes a static output which we can just upload to the server.
Another main reason having the ability to do i18n which is very important for us.

Right now the website is only one landing page and I'm ok with keeping it the way it is.
Let's have the design and content finalized and then move it to hugo.

It has some good https://gohugo.io/tools/starter-kits/ as well.

Resource: https://gohugo.io/content-management/multilingual/

### PR DESCRIPTION
**Pull request by AmirSavand**
Generated website: https://savandbros.com

Resolves #20

### CODE REVIEW

**Comment by Alir3z4** [comment]
Nice.
Please update read me about how to start working on this. Like installing
Hugo and useful command to work on the project.

Then merge and start on i18n

**Comment by Alir3z4** [comment]
You didn't use any starter ? Why not ?

**Comment by AmirSavand** [comment]
I created the project with huga command then built it.

**Comment by AmirSavand** [comment]
Note: You didn't approve it.

**Pull request merged**
